# Test data

TEST_STOCK_SYMBOL = "AAPL"
TEST_STOCK_SYMBOL2 = "MSFT"
TEXT_INDEX_SYMBOL = "NIFTY_50"

WATCHLIST_NAME = "W"
PORTFOLIO_NAME = "P"
ZERO_INVESTMENT_COUNT = "0"

QUANTITY = "1"
PURCHASE_DATE = "1/1/24"
PURCHASE_PRICE = "$1.00"
INVESTMENT_VALUE_AFTER_INVESTMENT_DELETE = "$0.00"
